import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import Header from "@/components/HeaderComponent";
import Footer from "@/components/FooterComponent";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Header />
        <main className="font-inter">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
